name: FIT4002 DASDD Client CI

on: [push, pull_request, workflow_dispatch]

jobs:
  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
        working-directory: ./client
  publish:
    name: Publish Images to Docker Hub
    needs:
      - install_dependencies
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          user: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Client Image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: imuh0001/fit4002-dasdd-client:latest
  deploy:
    name: Deploy to AWS Elastic Beanstalk
    needs:
      - install_dependencies
      - publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x '*.git*' '**/node_modules/*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "dasdd-client"
          environment_name: "dasdd-client-env"
          version_label: 1
          region: "ap-southeast-2"
          deployment_package: deploy.zip
          use_existing_version_if_available: true
